name: RealName
main: me.billybobjoe1223.RealName.RealName
version: 1.1.3
commands:
    rname:
        description: Returns a user's real name based on their display name.
        usage: /rname <displayname>
        aliases: [realname]
    dname:
        description: Returns a user's display name.
        usage: /dname <username>
        aliases: [displayname]