name: RealName
main: me.billybobjoe1223.RealName.RealName
version: 1.0.0
commands:
    rname:
        description: Returns a user's real name based on their display name.
        usage: /rname <displayname>
        aliases: [realname]
        permission: realname.rname